"""
forge.generators.game
======================
Complete mini-game generator for VoxelForge.

Given a game concept (genre, theme, size) this module generates:
  - All voxel assets (terrain / dungeon, buildings, characters, props)
  - A complete VoxelForge scene file wiring them all together
  - Lua game scripts (player controller, enemy AI, objective system)
  - A game manifest JSON describing every asset and script

The output is a fully playable mini-game that can be loaded in the
VoxelForge engine with a single command.

Example
-------
>>> from forge.generators.game import GameGenerator
>>> from forge.voxel import Palette
>>> gen = GameGenerator(Palette.natural(), seed=1)
>>> manifest = gen.generate(
...     title       = "Crystal Dungeon",
...     genre       = "dungeon",
...     theme       = "ice",
...     player_class= "mage",
...     enemies     = 3,
... )
>>> print(manifest["scene_path"])
>>> print(manifest["run_command"])
"""

from __future__ import annotations

import json
import os
import random
from typing import Any, Dict, List

from ..voxel import Palette, VoxelModel
from ..scene import Scene
from .terrain   import TerrainGenerator
from .buildings import BuildingGenerator
from .characters import CharacterGenerator
from .props      import PropGenerator
from .dungeon    import DungeonGenerator


# ---------------------------------------------------------------------------
# Genre presets
# ---------------------------------------------------------------------------

_GENRES: Dict[str, Dict[str, Any]] = {
    "village": {
        "level_type":     "terrain",
        "biome":          "grassland",
        "building_style": "medieval",
        "prop_mix":       ["tree", "barrel", "lamp_post", "chest"],
        "enemy_class":    "rogue",
        "enemy_armour":   "leather",
        "enemy_weapon":   "bow",
        "bg_color":       (0.05, 0.15, 0.30),
    },
    "dungeon": {
        "level_type":     "dungeon",
        "biome":          "grassland",
        "building_style": "medieval",
        "prop_mix":       ["crate", "chest", "rock", "barrel"],
        "enemy_class":    "warrior",
        "enemy_armour":   "chainmail",
        "enemy_weapon":   "axe",
        "bg_color":       (0.02, 0.02, 0.05),
    },
    "space": {
        "level_type":     "terrain",
        "biome":          "desert",
        "building_style": "sci-fi",
        "prop_mix":       ["crate", "rock", "lamp_post"],
        "enemy_class":    "mage",
        "enemy_armour":   "plate",
        "enemy_weapon":   "staff",
        "bg_color":       (0.0, 0.0, 0.08),
    },
    "fantasy": {
        "level_type":     "terrain",
        "biome":          "forest",
        "building_style": "fantasy",
        "prop_mix":       ["tree", "mushroom", "chest", "rock"],
        "enemy_class":    "mage",
        "enemy_armour":   "mage",
        "enemy_weapon":   "staff",
        "bg_color":       (0.03, 0.08, 0.03),
    },
    "horror": {
        "level_type":     "dungeon",
        "biome":          "forest",
        "building_style": "rustic",
        "prop_mix":       ["rock", "crate", "mushroom"],
        "enemy_class":    "rogue",
        "enemy_armour":   "leather",
        "enemy_weapon":   "axe",
        "bg_color":       (0.01, 0.0, 0.01),
    },
    "arctic": {
        "level_type":     "terrain",
        "biome":          "snow",
        "building_style": "sci-fi",
        "prop_mix":       ["rock", "crate", "barrel"],
        "enemy_class":    "warrior",
        "enemy_armour":   "plate",
        "enemy_weapon":   "sword",
        "bg_color":       (0.6, 0.75, 0.9),
    },
}


# ---------------------------------------------------------------------------
# Lua script templates
# ---------------------------------------------------------------------------

def _player_script(player_class: str, genre: str) -> str:
    speed = 14.0 if player_class in ("rogue", "archer") else 10.0
    jump  = 9.0  if player_class in ("warrior", "mage") else 7.0
    return f"""--[[
  VoxelForge Generated Player Controller
  Genre: {genre}  Class: {player_class}
  Auto-generated by VoxelForge GameGenerator
--]]

local SPEED = {speed}
local JUMP  = {jump}
local score = 0
local health = 100
local max_health = 100

function Start()
    print("[Player] {player_class.title()} ready!")
    if not RigidBody.HasRigidBody(self) then
        RigidBody.AddRigidBody(self)
    end
    RigidBody.SetMass(self, 1.0)
    RigidBody.SetUseGravity(self, true)
    RigidBody.SetIsStatic(self, false)
end

function Update()
    local dt = Time.DeltaTime()
    local vel = RigidBody.GetVelocity(self)
    local dx, dy = 0, 0

    if Input.GetKey("W") or Input.GetKey("Up")    then dy =  SPEED end
    if Input.GetKey("S") or Input.GetKey("Down")  then dy = -SPEED end
    if Input.GetKey("A") or Input.GetKey("Left")  then dx = -SPEED end
    if Input.GetKey("D") or Input.GetKey("Right") then dx =  SPEED end

    RigidBody.SetVelocity(self, dx, dy, vel.z)

    if Input.GetKeyDown("Space") then
        local pos = Transform.GetPosition(self)
        if pos.z <= 2.0 then
            RigidBody.SetVelocity(self, dx, dy, JUMP)
        end
    end

    -- Camera follow
    local pos = Transform.GetPosition(self)
    Camera.SetPosition(pos.x - 30, pos.y - 30, pos.z + 50)

    -- HUD
    UI.DrawText("HP: " .. health .. "/" .. max_health, 20, 20, 0.2, 1, 0.2, 1)
    UI.DrawText("Score: " .. score, 20, 50, 1, 1, 1, 1)

    if Input.GetKeyDown("Escape") then
        Engine.ExitGame()
    end
end

function TakeDamage(amount)
    health = health - (amount or 10)
    if health <= 0 then
        print("[Player] Game over! Final score: " .. score)
        health = 0
    end
end

function AddScore(points)
    score = score + (points or 10)
end

function End()
    print("[Player] Session ended. Score: " .. score)
end
"""


def _enemy_script(enemy_class: str, genre: str, index: int) -> str:
    """Build enemy Lua script using concatenation (avoids f-string/format vs Lua {} conflict)."""
    aggro = str(15.0 if genre in ("dungeon", "horror") else 10.0)
    idx   = str(index)
    return (
        "--[[\n  VoxelForge Enemy AI #" + idx + "\n"
        "  Genre: " + genre + "  Class: " + enemy_class + "\n"
        "--]]\n\n"
        "local AGGRO_DIST  = " + aggro + "\n"
        "local SPEED       = 6.0\n"
        "local ATTACK_DIST = 2.5\n"
        "local health      = 30\n"
        'local state       = "patrol"\n'
        "local patrol_timer = 0\n"
        "local patrol_dx, patrol_dy = 1, 0\n\n"
        "function Start()\n"
        '    print("[Enemy#' + idx + '] Spawned")\n'
        "    if not RigidBody.HasRigidBody(self) then\n"
        "        RigidBody.AddRigidBody(self)\n"
        "    end\n"
        "    RigidBody.SetMass(self, 1.0)\n"
        "    RigidBody.SetUseGravity(self, true)\n"
        "    RigidBody.SetIsStatic(self, false)\n"
        "end\n\n"
        "function Update()\n"
        "    local dt = Time.DeltaTime()\n"
        "    patrol_timer = patrol_timer + dt\n"
        "    if health <= 0 then ECS.DestroyEntity(self); return end\n"
        '    local player = ECS.FindEntityByName("player")\n'
        "    if not player then return end\n"
        "    local my_pos = Transform.GetPosition(self)\n"
        "    local pl_pos = Transform.GetPosition(player)\n"
        "    local dx = pl_pos.x - my_pos.x\n"
        "    local dy = pl_pos.y - my_pos.y\n"
        "    local dist = math.sqrt(dx*dx + dy*dy)\n"
        "    if dist < ATTACK_DIST then\n"
        '        state = "attack"\n'
        "        RigidBody.SetVelocity(self, 0, 0, RigidBody.GetVelocity(self).z)\n"
        "    elseif dist < AGGRO_DIST then\n"
        '        state = "chase"\n'
        "        local len = dist > 0 and dist or 1\n"
        "        RigidBody.SetVelocity(self, dx/len*SPEED, dy/len*SPEED,\n"
        "                              RigidBody.GetVelocity(self).z)\n"
        "    else\n"
        '        state = "patrol"\n'
        "        if patrol_timer > 3.0 then\n"
        "            patrol_timer = 0\n"
        "            local dirs = " + "{{1,0},{-1,0},{0,1},{0,-1}}" + "\n"
        "            local dir = dirs[math.random(#dirs)]\n"
        "            patrol_dx, patrol_dy = dir[1], dir[2]\n"
        "        end\n"
        "        RigidBody.SetVelocity(self, patrol_dx*SPEED*0.5,\n"
        "                              patrol_dy*SPEED*0.5,\n"
        "                              RigidBody.GetVelocity(self).z)\n"
        "    end\n"
        "end\n\n"
        "function TakeDamage(amount)\n"
        "    health = health - (amount or 10)\n"
        "end\n\n"
        "function End()\n"
        '    print("[Enemy#' + idx + '] Destroyed")\n'
        "end\n"
    )


def _objective_script(genre: str, collectibles: int) -> str:
    return (
        "--[[\n"
        "  VoxelForge Objective System\n"
        "  Genre: " + genre + "  Collectibles: " + str(collectibles) + "\n"
        "  Auto-generated by VoxelForge GameGenerator\n"
        "--]]\n\n"
        "local total_chests   = " + str(collectibles) + "\n"
        "local opened_chests = 0\n"
        "local win = false\n\n"
        'function Start()\n'
        '    print("[Objective] Find and open " .. total_chests .. " chests to win!")\n'
        'end\n\n'
        'function Update()\n'
        '    if win then return end\n'
        '    local player = ECS.FindEntityByName("player")\n'
        '    if not player then return end\n'
        '    local pl_pos = Transform.GetPosition(player)\n'
        '    local chests = ECS.FindEntitiesByNameContaining("chest")\n'
        '    for _, chest in ipairs(chests or {}) do\n'
        '        local cp = Transform.GetPosition(chest)\n'
        '        local dx = pl_pos.x - cp.x\n'
        '        local dy = pl_pos.y - cp.y\n'
        '        if math.sqrt(dx*dx + dy*dy) < 3.0 and Input.GetKeyDown("E") then\n'
        '            ECS.DestroyEntity(chest)\n'
        '            opened_chests = opened_chests + 1\n'
        '            print("[Objective] " .. opened_chests .. "/" .. total_chests)\n'
        '            if opened_chests >= total_chests then\n'
        '                win = true\n'
        '                print("[Objective] YOU WIN!")\n'
        '            end\n'
        '        end\n'
        '    end\n'
        '    UI.DrawText("Chests: "..opened_chests.."/"..total_chests, 20, 80, 1,0.9,0.1,1)\n'
        'end\n'
    )


# ---------------------------------------------------------------------------
# GameGenerator
# ---------------------------------------------------------------------------

class GameGenerator:
    """
    Generates a complete mini-game package.

    Parameters
    ----------
    palette : Palette
    seed    : int
    output_dir : str
        Root directory for generated assets and scripts.
    """

    def __init__(self, palette: Palette, seed: int = 0,
                 output_dir: str = "generated_assets"):
        self.palette    = palette
        self._rng       = random.Random(seed)
        self._seed      = seed
        self.output_dir = output_dir

    # ------------------------------------------------------------------
    def generate(
        self,
        title:        str = "VoxelForge Game",
        genre:        str = "village",
        theme:        str = "",
        player_class: str = "warrior",
        enemies:      int = 3,
        props:        int = 6,
        level_size:   int = 48,
    ) -> Dict[str, Any]:
        """
        Generate a complete mini-game.

        Returns a manifest dict with all paths and a run_command.
        """
        g       = _GENRES.get(genre, _GENRES["village"])
        slug    = title.lower().replace(" ", "_")[:20]
        game_dir = os.path.join(self.output_dir, "games", slug)

        assets_dir  = os.path.join(game_dir, "assets")
        scripts_dir = os.path.join(game_dir, "scripts")
        scenes_dir  = os.path.join(game_dir, "scenes")
        for d in (assets_dir, scripts_dir, scenes_dir):
            os.makedirs(d, exist_ok=True)

        manifest: Dict[str, Any] = {
            "title":    title,
            "genre":    genre,
            "theme":    theme or g.get("biome", "grassland"),
            "seed":     self._seed,
            "assets":   [],
            "scripts":  [],
        }

        scene = Scene(background_color=g["bg_color"])

        # --- Level geometry ---
        level_path = self._generate_level(
            game_dir, assets_dir, g, theme or g.get("biome", "grassland"),
            level_size, manifest
        )
        scene.add_voxel_model("level", level_path, position=(0, 0, 0),
                               is_static=True)
        surface_z = 14.0

        # --- Player ---
        cgen   = CharacterGenerator(self.palette, seed=self._seed + 100)
        p_model = cgen.generate(
            class_type = player_class, skin_tone="tan", hair_color="brown",
            armour     = "plate" if player_class == "warrior" else "mage",
            weapon     = "sword" if player_class == "warrior" else "staff",
            name       = "player",
        )
        p_path = os.path.join(assets_dir, "player.vox")
        p_model.save(p_path)
        manifest["assets"].append({"name": "player", "path": p_path, "type": "character"})
        player_entity = scene.add_voxel_model(
            "player", p_path,
            position=(float(level_size // 2), float(level_size // 2), surface_z),
            is_static=False, add_rigidbody=True,
        )

        # --- Player script ---
        p_script = _player_script(player_class, genre)
        p_script_path = os.path.join(scripts_dir, "player.lua")
        with open(p_script_path, "w") as f:
            f.write(p_script)
        manifest["scripts"].append({"name": "player", "path": p_script_path})
        player_entity["LuaScript"] = {
            "scriptPath": scripts_dir, "scriptName": "player.lua"
        }

        # --- Enemies ---
        e_class  = g["enemy_class"]
        e_armour = g["enemy_armour"]
        e_weapon = g["enemy_weapon"]
        for i in range(enemies):
            e_model = CharacterGenerator(self.palette, seed=self._seed + 200 + i).generate(
                class_type = e_class, skin_tone="dark", hair_color="black",
                armour=e_armour, weapon=e_weapon, name=f"enemy_{i}",
            )
            e_path = os.path.join(assets_dir, f"enemy_{i}.vox")
            e_model.save(e_path)
            manifest["assets"].append({"name": f"enemy_{i}", "path": e_path, "type": "character"})

            ex = float(self._rng.randint(4, level_size - 8))
            ey = float(self._rng.randint(4, level_size - 8))
            e_entity = scene.add_voxel_model(
                f"enemy_{i}", e_path,
                position=(ex, ey, surface_z),
                is_static=False, add_rigidbody=True,
            )
            e_script = _enemy_script(e_class, genre, i)
            e_script_path = os.path.join(scripts_dir, f"enemy_{i}.lua")
            with open(e_script_path, "w") as f:
                f.write(e_script)
            manifest["scripts"].append({"name": f"enemy_{i}", "path": e_script_path})
            e_entity["LuaScript"] = {
                "scriptPath": scripts_dir, "scriptName": f"enemy_{i}.lua"
            }

        # --- Props (some are chests = collectibles) ---
        prop_types = g.get("prop_mix", ["tree", "crate", "chest", "rock"])
        pgen       = PropGenerator(self.palette, seed=self._seed + 300)
        chest_count = 0

        for i in range(props):
            ptype = prop_types[i % len(prop_types)]
            p_name = f"prop_{ptype}_{i}"
            p_model = pgen.generate(ptype, name=p_name)
            pp_path = os.path.join(assets_dir, f"{p_name}.vox")
            p_model.save(pp_path)
            manifest["assets"].append({"name": p_name, "path": pp_path, "type": "prop"})
            px = float(self._rng.randint(2, level_size - 4))
            py = float(self._rng.randint(2, level_size - 4))
            scene.add_voxel_model(
                p_name, pp_path,
                position=(px, py, surface_z),
                is_static=True,
            )
            if ptype == "chest":
                chest_count += 1

        # --- Objective script ---
        obj_script = _objective_script(genre, chest_count)
        obj_path   = os.path.join(scripts_dir, "objective.lua")
        with open(obj_path, "w") as f:
            f.write(obj_script)
        manifest["scripts"].append({"name": "objective", "path": obj_path})
        # Attach to first entity (world entity)
        if scene._entities:
            scene._entities[0]["LuaScript"] = {
                "scriptPath": scripts_dir, "scriptName": "objective.lua"
            }

        # --- Ambient light ---
        scene.add_point_light("sun",
            position=(float(level_size//2), float(level_size//2), 50.0),
            color=(1.0, 0.95, 0.85), intensity=2.0,
            range_=float(level_size * 3))

        # --- Save scene ---
        scene_path = os.path.join(scenes_dir, f"{slug}.scene")
        scene.save(scene_path)
        manifest["scene_path"] = scene_path

        # --- Manifest JSON ---
        manifest_path = os.path.join(game_dir, "manifest.json")
        with open(manifest_path, "w") as f:
            json.dump(manifest, f, indent=2)
        manifest["manifest_path"] = manifest_path
        manifest["entity_count"]  = scene.entity_count
        manifest["run_command"]   = (
            f"cd engine && ./voxelforge --scene ../{scene_path}"
        )

        return manifest

    # ------------------------------------------------------------------
    def _generate_level(
        self, game_dir: str, assets_dir: str,
        g: Dict[str, Any], theme: str,
        size: int, manifest: Dict[str, Any],
    ) -> str:
        if g["level_type"] == "dungeon":
            dgen  = DungeonGenerator(self.palette, seed=self._seed)
            model = dgen.generate(size, size, wall_height=3,
                                   style=theme if theme in ("stone","dungeon","cave","ice") else "dungeon")
        else:
            tgen  = TerrainGenerator(self.palette, seed=self._seed)
            model = tgen.generate(size, size, max_depth=14, biome=g["biome"])

        path = os.path.join(assets_dir, "level.vox")
        model.save(path)
        manifest["assets"].append({"name": "level", "path": path, "type": "level"})
        return path
